version: '2'

services:
  taiga:
    build: .
    ports:
      - 80:80
      # - 443:443 # To enable SSL, uncomment this line
    depends_on:
      - postgres
    env_file: 
      - config.env
    volumes:
      # I recommend specifying a volume that maps to taiga's media,
      # this way uploaded files are not lost during upgrades of the taiga image
      - ./media:/usr/src/taiga-back/media

      # If you'd like to store the configuration outside of the container,
      # uncomment this volume. This allows for easy changes to the configuration.
      # - ./conf/taiga:/taiga

      # - ./ssl.crt:/etc/nginx/ssl/ssl.crt:ro # To enable SSL, uncomment this line
      # - ./ssl.key:/etc/nginx/ssl/ssl.key:ro # To enable SSL, uncomment this line
      

  postgres:
    image: postgres:10.4-alpine
    env_file: 
      - config.env
    ports:
      - 5432
    volumes:
      # this helps prevent your postgres data from deleted
      - ./pgdata:/var/lib/postgresql/data
